---

- name: Install Percona Repository
  yum:
    name={{ item }}
    state=present
  become: yes
  become_method: sudo 
  with_items: "{{ percona_mysql_repo }}"

- name: Install EPEL Repository
  yum:
    name={{ item }}
    state=present
  become: yes
  become_method: sudo
  with_items: "{{ epel_repo }}"

